module.exports = {
  reactStrictMode: true,
  env:{NEXT_PUBLIC_CONTRACTADDRESS:process.env.NEXT_PUBLIC_CONTRACTADDRESS,
     NEXT_PUBLIC_NFTCONTRACTADDRESS:process.env.NEXT_PUBLIC_NFTCONTRACTADDRESS
        }
}
